project:
  type: book

book:
  title: "Spatial Science and Remote Sensing"
  author: "Julian Siebert"
  date: "19.3.2024"
  chapters:
    - index.qmd
    - references.qmd
    - data-intro.qmd
    - data-sources.qmd
    - appli-intro.qmd
    - stat-intro.qmd
    - map-intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

