Here i want to list all types of spatial data and how to access them in a reasonable way. (API´s) etc.

## Collections

- [free-datasets-APIs](https://github.com/nenalukic/free-datasets-APIs/tree/main) A collection on github of freely available datasets and APIs for different topics like weather, agriculture, etc.


## API´s

- [Request to an WMS (Web Map Service)](https://www.geodaten.niedersachsen.de/startseite/allgemeine_informationen/downloads/leitfaden_und_checklisten/leitfaeden-der-gdi-ni-127645.html)
- [Earth Engine Data Catalog](https://developers.google.com/earth-engine/datasets)



## Databases
- [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/hvdshome) der EU mit Daten zu Umwelt, Landwirtschaft, etc.
- [Agri4Cast](https://agri4cast.jrc.ec.europa.eu/DataPortal/Index.aspx) Ressources Portal der EU enthält Daten zur Landwirtschaft, Wetter, Boden, etc.

## Satellite Data

- [rsi-package](https://www.mm218.dev/posts/2024-01-10-rsi-cran/) to download satellite images also here https://geocompx.org/post/2024/rsi-bp1/

## Weather Data

- [WorldClim](https://www.worldclim.org/data/worldclim21.html) WorldClim is a set of global climate layers (climate grids) with a spatial resolution of about 1 km². It is based on weather station data and provides information on temperature and precipitation. The data is available as raster files and can be accessed via an API. There might be an [R package](https://brunomioto.github.io/WorldClimData/) to download data from WorldClimData.
    + Mean, minimum, and maximum temperature
    + Precipitation
    + Solar radiation
    + Wind speed
- [ERA5](https://www.ecmwf.int/en/forecasts/datasets/reanalysis-datasets/era5) ERA5 is a reanalysis dataset that provides global weather data at a resolution of 0.25°. It is based on a combination of weather station data, satellite data, and weather models. The data is available as raster files and can be accessed via an API. The API is documented [here](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form).
    + Temperature
    + Precipitation
    + Wind speed
    + Solar radiation
    + Humidity
- [CHIRPS](https://www.chc.ucsb.edu/data/chirps) CHIRPS is a global rainfall dataset that provides information on precipitation at a resolution of 0.05°. It is based on a combination of weather station data and satellite data. The data is available as raster files and can be accessed via an API. The API is documented [here](https://www.chc.ucsb.edu/data/chirps).

### Precipitation Data

- [pRecipe](https://cran.r-project.org/web/packages/pRecipe/vignettes/introduction.html) Package in R makes a lot of common precipitation data accessible. There is a video on how to do this [here](https://www.youtube.com/watch?v=9Ex-f66qe2w)

## Soil Data

- [Soilgrids](https://soilgrids.org/) Soilgrids is a global gridded soil information system operating at a resolution of 250 m. It is based on machine learning and remote sensing and provides soil information for the entire globe. This data is not actually measured and was shown to underestimate extreme soil distributions. It is available as a raster file and can be accessed via an API. The API is documented [here](https://rest.soilgrids.org/query.html). And there is a soilgrids [r package](https://github.com/one-acre-fund/soilgrids).
    + Percentage of sand, silt, clay
    + Bulk density
    + Organic carbon content
    + pH
    + Cation exchange capacity
-[WoSIS](https://www.isric.org/accessing-wosis-using-r) contains harmonized soil data from all over the globe. It is actually measured data. The way to access it with R is described [here](https://git.wur.nl/Batje001/wosis/-/tree/master/R_scripts)


## Drought Data

- [GDO / CDI](https://edo.jrc.ec.europa.eu/gdo/php/index.php?id=2112) Global Drought Observatory with the Combined Drought Inidicator (CDI) provides information about changes in drought indicators for europe and worldwide.


## Land Use Data

- [Copernicus Global Land Service](https://land.copernicus.eu/global/) The Copernicus Global Land Service provides information on land cover and land use at a global scale. It is based on satellite data and provides information on land cover, land use, and changes in land cover over time. The data is available as raster files and can be accessed via an API.
- [EuroCrops Dataset](https://zenodo.org/records/10118572) from Zenodo is a open source dataset which tries to provide information about the crop type of each individual field in a unified an machine-readable syntax.

## Location / Mobility Data

 - [openroute service](https://openrouteservice.org/) provides an API and a [R package](https://github.com/GIScience/openrouteservice-r) to access routing and isochrone data.